#NUMPY


In [1]:
import numpy as np

In [22]:
arr = np.random.randint(100,1001,size=50)

In [23]:
arr

array([790, 903, 881, 440, 971, 561, 119, 370, 317, 332, 518, 538, 880,
       531, 754, 784, 975, 367, 730, 156, 938, 182, 325, 664, 621, 265,
       599, 206, 762, 607, 761, 182, 431, 153, 487, 833, 283, 243, 959,
       236, 460, 325, 759, 971, 701, 544, 292, 257, 795, 683])

min, max, mean, median, standard deviation.

In [24]:
max=np.max(arr)
min=np.min(arr)
mean=np.mean(arr)
median=np.median(arr)
std=np.std(arr)

In [25]:
min,max,mean,median,std

(np.int64(119),
 np.int64(975),
 np.float64(548.82),
 np.float64(541.0),
 np.float64(261.3148055506997))

values between 300 and 700

In [26]:
values_between_300_and_700 = arr[(arr >= 300) & (arr <= 700)]
values_between_300_and_700

array([440, 561, 370, 317, 332, 518, 538, 531, 367, 325, 664, 621, 599,
       607, 431, 487, 460, 325, 544, 683])

In [29]:
result = np.where(arr>800,800,arr)
arr


array([790, 903, 881, 440, 971, 561, 119, 370, 317, 332, 518, 538, 880,
       531, 754, 784, 975, 367, 730, 156, 938, 182, 325, 664, 621, 265,
       599, 206, 762, 607, 761, 182, 431, 153, 487, 833, 283, 243, 959,
       236, 460, 325, 759, 971, 701, 544, 292, 257, 795, 683])

In [30]:
result

array([790, 800, 800, 440, 800, 561, 119, 370, 317, 332, 518, 538, 800,
       531, 754, 784, 800, 367, 730, 156, 800, 182, 325, 664, 621, 265,
       599, 206, 762, 607, 761, 182, 431, 153, 487, 800, 283, 243, 800,
       236, 460, 325, 759, 800, 701, 544, 292, 257, 795, 683])

In [32]:
resh=np.reshape(arr,(5,10))
resh

array([[790, 903, 881, 440, 971, 561, 119, 370, 317, 332],
       [518, 538, 880, 531, 754, 784, 975, 367, 730, 156],
       [938, 182, 325, 664, 621, 265, 599, 206, 762, 607],
       [761, 182, 431, 153, 487, 833, 283, 243, 959, 236],
       [460, 325, 759, 971, 701, 544, 292, 257, 795, 683]])

In [33]:
row_sums = np.sum(resh, axis=1)
col_sums = np.sum(resh, axis=0)
row_means = np.mean(resh, axis=1)
col_means = np.mean(resh, axis=0)

print("Row Sums:", row_sums)
print("Column Sums:", col_sums)
print("Row Averages:", row_means)
print("Column Averages:", col_means)

Row Sums: [5684 6233 5169 4568 5787]
Column Sums: [3467 2130 3276 2759 3534 2987 2268 1443 3563 2014]
Row Averages: [568.4 623.3 516.9 456.8 578.7]
Column Averages: [693.4 426.  655.2 551.8 706.8 597.4 453.6 288.6 712.6 402.8]


Generate two 1D arrays of random integers (size 50).

In [34]:
array1 = np.random.randint(0, 100, size=50)
array2 = np.random.randint(0, 100, size=50)

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [60 31 33 77 89 48 30 31 79 63 69 19 33 58 65 69 47 24  5 62 76 90 69 34
 27 45 69 57 79 17 20 66 92 64  7 15 38 93 88 95 82 30  1 72 96 32 96 32
 22 50]
Array 2: [48 64 82 22 28 40  4 40  3 15 29 37 54 16 63 31 53 41 41 74 96 90 97 51
 43 27 16  6 51 39 15 67 13 24 66 77  9 75 30 30 35 28 86 42 99 10 38 92
 62 22]


corelation and covariance

In [37]:
crr=np.corrcoef(array1,array2)
display(crr)

array([[ 1.        , -0.04078321],
       [-0.04078321,  1.        ]])

In [39]:
cov = np.cov(array1, array2)
display(cov)

array([[752.56489796, -30.33306122],
       [-30.33306122, 735.06489796]])